# Generated by Django 5.2.6 on 2025-10-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
